### ISSUE TITLE
Excessive CPU utilization when looking for a term in the file.

### ISSUE THREAD

**Issue by fbonecco-cribl** [whargrove/qlog#3]
Hi @whargrove this is Franco from Cribl. Please see the scenario below. I'm seeing the application consuming +250% of CPU on my laptop when:
- specifying a term that can't be found easily (i.e. at the end of the file) AND/OR
`curl -v  "http://localhost:8080/queryLog?relativePath=large.csv&count=1&filter=cribl`
- when asking the service for too many lines:
`curl -v  "http://localhost:8080/queryLog?relativePath=large.csv&count=999999999`

*Where `large.csv` is a `4.3GB` file with 28,741,648 lines that doesn't contain the searched term `cribl`.

![image](https://github.com/whargrove/qlog/assets/77752546/def53c4f-d782-4e4b-b5e0-72819dbf94ca)

Can you please take a look at each case and see whether this is expected behavior or there's something you can do to improve perf?

Thanks!

Environment:
![image](https://github.com/whargrove/qlog/assets/77752546/1178af1c-8ff4-441f-92ba-7bb96fe16bce)

**Comment by whargrove** [comment]
👋🏻 Hi @fbonecco-cribl, thank you for taking a look here.

To confirm, the examples you list here _do complete_ and in both cases the time complexity of reading the file is `O(n)` for the size of the file.

```shell
% time curl -Ss "http://localhost:8080/queryLog?relativePath=access.log&count=1&filter=cribl" >/dev/null 
curl -Ss  > /dev/null  0.00s user 0.00s system 0% cpu 7.860 total

% time curl -Ss "http://localhost:8080/queryLog?relativePath=access.log&count=999999999" >/dev/null
curl -Ss  > /dev/null  0.05s user 0.27s system 0% cpu 3:19.33 total
```

(The service is running in a container, so `time` will not accurately report the CPU utilization. `docker stats qlog` confirms the high CPU utilization for both scenarios.)

The second example is impacted by the unbounded response size and overhead of JSON serialization. On my system, both requests finish reading the file in ~8s (repesenting the `O(n)` of the file size) but the second request is essentially asking for all lines in the large file to be returned: no filter, arbitrarily large line count, a large file at the path given.

An initial tack to improve performance would be to implement pagination in the API interface.

## Pagination

Add an additional parameter to the `/queryLog` endpoint: `start` with a default value of 0. Set a larger default value for `count` (1000) and enforce a max value of 10000.

Using a combination of `start` and `count`, a client could request lines from the file over multiple requests to the server. E.g.,

1. `start=0&count=1000` (first page)
2. `start=1000&count=1000` (second page)
3. ... and so on

Advantages:

- Bounded response sizes means the server won't spend CPU time serializing an essentially unbounded file.
- Preserve JSON content type for portability of client integration.

Disadvantages:

- A naive implementation might cause inconsistent pagination results if the file size changes between subsequent requests. This can be mitigated by serializing the byte offset (as the size of the file) when the first pagination request is served as a "pagination token" and include it in the response payload. The server can re-use the token on N+1 request to start reading the file at the given byte offset.
- Each paginated request would need to read the entire file from disk even if the request is actually interested in a region of the file (according to the start/count parameters). An interesting approach to mitigate this would be the retain a memory-mapped region of the file for subsequent reads. We could improve from the "pagination token" concept introduced above and return the offset of the last byte read from the file (in the current window) in the response payload. The server would retain the next chunk as a memory mapped file to avoid having to re-read the file from the tail to the position in the cursor.

## Other

Other than implementing pagination there are some other areas that could improve performance/throughput:

1. Implement Streaming Responses. A streaming implementation would emit lines from the server as they are collected instead of waiting to read the entire file before the response is sent. I'd lean on the [reactor](https://projectreactor.io/) library to provide the plumbing for publish lines from the file. (Micronaut has first-class integration with reactor.)
2. Explore alternative content-type, e.g. protocol buffers. JSON serialization has a large amount of overhead especially on JVM services where strings are allocated on the heap and require garbage collection. Protocol Buffers would offer a much more efficient serialization but would require clients to implement support for proto response.

**Comment by whargrove** [comment]
It's worth pointing on that the current implementation is searching a file for a matching line up to (and not exceeding) the number of lines specified in the count. Changing the semantics of the API may also be a viable option to improve performance.

In the current form a request like: `curl -v  "http://localhost:8080/queryLog?relativePath=large.csv&count=1&filter=cribl"` is semantically equivalent to `grep "cribl" /var/log/large.csv | tail -r -n1`. That is, it will search for all line matches in a file and then return the "newest" N entries in the file.

Instead, `tail -r -n1 | grep "filter"` would search in the last line for a matching entry. Coupled with a pagination implementation (as proposed above) would allow a client to search for matching entries through a file.

**Comment by fbonecco-cribl** [comment]
Thanks @whargrove for looking into this issue.

Regarding this statement:

> To confirm, the examples you list here do complete and in both cases the time complexity of reading the file is O(n) for the size of the file.

That's a good point and I forgot to mention that, at least in the first example, the request doesn't seem to return. Take a look at the following output. In this case, the request ended after 5m (think it might have killed by the `time` command itself).

`franco@franco:~/workspace/whargrove/qlog$ time curl  "http://localhost:8080/queryLog?relativePath=large.csv&filter=cribl"  > /dev/null  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:05:00 --:--:--     0
curl: (52) Empty reply from server

real	5m0,117s
user	0m0,025s
sys	0m0,051s
`

Another run ended after some minutes too with the following message (curl), which I don't think is what the API should respond with (I get `{}` in other cases where the application can't find a given term).
`curl: (52) Empty reply from server`
And when this happens, the application seems to be doing something in the backend:
![image](https://github.com/whargrove/qlog/assets/77752546/ab7eb49a-d112-457d-9be7-46872c194d1a)

Worth mentioning that I'm still using the 4.3GB CSV file and that the term cribl doesn't exist in the file.

Adding pagination is a great initiative but I suspect that there's something else going that's causing this odd behavior. Do you want to take another look?

**Comment by whargrove** [comment]
Ah! Thanks for clarifying the behavior @fbonecco-cribl.

I can reproduce the issue you're experiencing and agree it's not expected behavior. There was a bug in the reader where an integer overflow occured and created a scenario where the reader would enter infinite loop and never progress further reading the file.

I needed to generate a larger file on my side. The one I've been testing with was just under 2GB and therefore within the max value for 32-bit integer in Java.

#7 addresses this bug related to integer overflow and adds some logging to the server so that it is more obvious to confirm the file read is completed. (Perhaps more useful for the second case you identified in the original message.)

>In this case, the request ended after 5m

Both micronaut and curl have default idle timeouts set to 5m. This is configurable in micronaut with [micronaut.server.write-idle-timeout](https://docs.micronaut.io/latest/guide/configurationreference.html#io.micronaut.http.server.HttpServerConfiguration) and in `curl` using the `-m` flag.

To address idle timeout issues the reader would require refactoring to:
1. Publish lines as they are found by the reader. (Micronaut would use a `transfer-encoding: chunked` header in the response. Supporting HTTP/2 would further improve performance.)
2. Implement a timeout around the reader and return a `504 Gateway Timeout` error messages instead of closing the connection unexpectedly.

---

N.B. there's an altogether different approach the server could take to serving files. I originally imagined the service to function as a sidecar and require zero processing to be able to start serving requests. If large files (>2GB) are required by this service we'd need to go down a path where files are ingested and indexed by the service prior to serving.

If the large files are relatively static (they don't change often) then ingesting the files into a columnar format such as parquet and mapping the lines in the files to a schema would allow for predicate pushdown to more efficiently read only the lines required to serve a query.

If write volume is high then a technique like Log Structured Merge Trees may be a good approach to efficiently index the files and serve queries for live log files. We'd also want to implement a retention policy or tiered storage to limit to total size of files that the service is capable of serving live.

**Comment by whargrove** [comment]
@fbonecco-cribl I've added #8 that introduces a timeout and explicit error handling.

**Comment by fbonecco-cribl** [comment]
Thanks @whargrove! Indeed, the issue is gone now. Nice work!
